import Link from 'next/link'

export default function TermsPage() {
  const s = (size: number, weight: number = 400, color = '#0f0f0f'): React.CSSProperties => ({
    fontSize: size, fontWeight: weight, color, lineHeight: 1.7, marginBottom: 12,
  })

  const sections = [
    {
      title: '1. No Legal Advice — Ever',
      body: 'Law OSS is software. It is not a law firm, not a legal service provider, and not a substitute for a licensed attorney. Nothing generated by Law OSS — including research summaries, contract analysis, clause suggestions, litigation strategy, regulatory mapping, or any other output — constitutes legal advice, legal opinion, or an attorney-client relationship. You must independently verify every output with a qualified attorney licensed in your jurisdiction before taking any legal action or relying on any analysis. The User bears sole and absolute responsibility for all decisions made in reliance on Law OSS output.',
    },
    {
      title: '2. Beta Software — Experimental and Unverified',
      body: 'Law OSS is pre-release beta software. It may be incomplete, inaccurate, or unreliable at any time without notice. AI language models used within the platform are known to hallucinate — fabricating statutes, case citations, regulatory provisions, and legal reasoning that sound plausible but do not exist or are materially incorrect. You must treat all AI-generated legal content as unverified and conduct independent legal research before any reliance. Do not upload confidential, privileged, sensitive, or client-identifying documents to this platform. You assume all risk associated with such uploads.',
    },
    {
      title: '3. Bring Your Own Key (BYOK)',
      body: 'Law OSS does not include AI inference. You must supply your own API keys from providers such as Anthropic (Claude) or Google (Gemini). Your key is stored encrypted at rest using AES-256 and is used solely to route your requests to the AI provider. You are solely responsible for your API key security, your usage costs billed directly by the AI provider, and compliance with that provider\'s terms of service. Law OSS charges nothing for AI usage. If your key is compromised, Law OSS bears no liability for any resulting charges or data exposure.',
    },
    {
      title: '4. Data Handling',
      body: 'Authentication and account data is handled by Supabase. Uploaded documents are stored in Supabase Storage. Conversation and session data may be retained to support continuity. We do not sell, license, or share your data with third parties for commercial purposes. We do not use your data to train AI models. Your messages are processed by your chosen AI provider (Anthropic, Google, etc.) subject to their independent terms of service and privacy policies, which you should review. We are not responsible for how AI providers handle data transmitted to them.',
    },
    {
      title: '5. Absolute Disclaimer of Warranties',
      body: 'LAW OSS IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, LAW OSS AND ITS AUTHORS, CONTRIBUTORS, MAINTAINERS, OPERATORS, AFFILIATES, LICENSORS, AND SUCCESSORS ("PROVIDERS") EXPRESSLY DISCLAIM ALL WARRANTIES INCLUDING, WITHOUT LIMITATION: (A) WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT; (B) WARRANTIES THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF VIRUSES OR HARMFUL COMPONENTS; (C) WARRANTIES AS TO THE ACCURACY, COMPLETENESS, RELIABILITY, CURRENCY, OR LEGAL VALIDITY OF ANY AI-GENERATED OUTPUT; AND (D) ANY IMPLIED WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE OF TRADE. NO ORAL OR WRITTEN INFORMATION OR ADVICE PROVIDED BY ANY PROVIDER SHALL CREATE ANY WARRANTY.',
    },
    {
      title: '6. Limitation of Liability — Zero',
      body: 'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL ANY PROVIDER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, EXEMPLARY, OR NOMINAL DAMAGES WHATSOEVER, INCLUDING BUT NOT LIMITED TO: (A) LOSS OF PROFITS, REVENUE, DATA, BUSINESS, OR GOODWILL; (B) PERSONAL INJURY OR PROPERTY DAMAGE OF ANY NATURE; (C) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR DATA; (D) ERRORS, INACCURACIES, OR OMISSIONS IN ANY AI-GENERATED OUTPUT; (E) RELIANCE ON ANY LEGAL ANALYSIS, RESEARCH, OR DOCUMENT PRODUCED BY THE PLATFORM; (F) MISSED DEADLINES, STATUTES OF LIMITATIONS, OR PROCEDURAL DEFAULTS ARISING FROM USE OF OR INABILITY TO USE THE SERVICE; OR (G) ANY OTHER MATTER RELATING TO THE SERVICE — WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, STATUTE, OR ANY OTHER THEORY — EVEN IF PROVIDERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. BECAUSE LAW OSS IS OFFERED FREE OF CHARGE AS OPEN SOURCE SOFTWARE, THE TOTAL AGGREGATE LIABILITY OF ALL PROVIDERS TO YOU FOR ANY CLAIMS ARISING FROM OR RELATED TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED ZERO DOLLARS ($0.00). SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES; IN SUCH JURISDICTIONS, OUR LIABILITY IS LIMITED TO THE MINIMUM AMOUNT PERMITTED BY LAW.',
    },
    {
      title: '7. Indemnification',
      body: 'You agree to defend, indemnify, and hold harmless all Providers from and against any and all claims, damages, losses, costs, liabilities, and expenses (including reasonable attorneys\' fees) arising out of or in any way connected with: (a) your access to or use of Law OSS; (b) your violation of these Terms; (c) your violation of any third-party right, including any intellectual property right or privacy right; (d) any content you upload, submit, or transmit through the platform; or (e) your reliance on any AI-generated output. This indemnification obligation survives termination of these Terms and your use of the platform.',
    },
    {
      title: '8. Professional Responsibility',
      body: 'Legal professionals using Law OSS remain fully subject to their applicable rules of professional conduct (including the ABA Model Rules, state bar rules, SRA Code, or equivalent). You are responsible for: supervising and verifying AI output before use in any client matter; maintaining client confidentiality and not uploading client-identifying data without informed written consent; ensuring that AI-generated work product meets applicable professional standards; and disclosing the use of AI tools to clients as required by your jurisdiction. Law OSS is not a "legal information service" under any statutory definition and does not register or supervise legal professionals.',
    },
    {
      title: '9. Fees, Credits, and Third-Party Costs',
      body: 'Some features of Law OSS may be free, metered, usage-limited, or subject to a paid plan. We reserve the right to introduce, modify, or remove fees, subscription plans, credits, quotas, or usage limits at any time. Where required by law, we will provide reasonable advance notice of material fee changes. Credits or usage allowances have no cash value, are non-transferable, and expire as stated at the time of issuance. If you connect your own third-party AI provider API keys (such as Anthropic or Google), you are solely responsible for all charges, overage costs, usage limits, rate restrictions, and any terms imposed by those providers — Law OSS has no visibility into or control over those costs, and accepts no liability for them. Unless expressly stated otherwise at the time of purchase, all fees paid to Law OSS are non-refundable except where required by applicable law.',
    },
    {
      title: '10. Intellectual Property and Open Source',
      body: 'Certain Law OSS software is made available under open-source licences. Your use of that software is governed by the applicable open-source licence terms. The open-source licence applies to the source code only — it does not extend to the hosted Service or any of the elements described below. The Law OSS hosted Service, website, brand, trade names, logos, visual design, hosted infrastructure, documentation, compiled platform, and all non-open-source elements are owned exclusively by Law OSS or its licensors and are protected by intellectual property, unfair competition, and other applicable laws. Nothing in these Terms or the open-source licence grants you any right to use the "Law OSS" name, logo, or branding in connection with any commercial product, competing service, or derivative platform, or to represent your work as the official Law OSS product or as endorsed by its maintainers.',
    },
    {
      title: '11. Access, Availability, and Termination',
      body: 'Law OSS is provided on a best-effort basis. We reserve the right to modify, suspend, restrict, or discontinue the service (or any part of it) at any time without notice or liability. We may terminate or suspend your access immediately, without prior notice or liability, for any reason, including if you breach these Terms. Upon termination, your right to use the service ceases immediately. Provisions that by their nature should survive termination shall survive, including Sections 5, 6, 7, and 11.',
    },
    {
      title: '12. Governing Law and Dispute Resolution',
      body: 'These Terms and any dispute or claim arising out of or in connection with them (including non-contractual disputes) are governed exclusively by the laws of the State of New York, United States, without regard to its conflict of law provisions. You irrevocably consent to the exclusive jurisdiction of the state and federal courts located in New York County, New York for the resolution of any dispute. The United Nations Convention on Contracts for the International Sale of Goods does not apply. Any cause of action you may have with respect to the service must be commenced within one (1) year after the claim arises.',
    },
    {
      title: '13. Miscellaneous',
      body: 'These Terms constitute the entire agreement between you and Law OSS Providers with respect to the subject matter herein and supersede all prior agreements. If any provision is found unenforceable, that provision shall be modified to the minimum extent necessary to make it enforceable, and the remainder shall continue in full force. Our failure to enforce any right or provision is not a waiver. You may not assign or transfer your rights under these Terms without our prior written consent. We may assign our rights without restriction. These Terms do not create any partnership, joint venture, employment, or agency relationship. Section headings are for convenience only.',
    },
    {
      title: '14. Changes to Terms',
      body: 'We reserve the right to update these Terms at any time. The "Last updated" date at the top of this page will reflect any changes. If we make material changes, we will provide reasonable notice through the platform. Your continued use of Law OSS after the effective date of any revision constitutes your acceptance of the updated Terms. If you do not agree to the revised Terms, you must stop using the platform.',
    },
  ]

  return (
    <div style={{ minHeight: '100vh', background: '#fff' }}>
      <nav style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '0 48px', height: '60px', borderBottom: '1px solid rgba(0,0,0,0.08)',
      }}>
        <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none', color: '#0f0f0f' }}>
          <div style={{
            width: 30, height: 30, background: '#0f0f0f', borderRadius: 7,
            display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: 14,
          }}>⚖</div>
          <span style={{ fontWeight: 700, fontSize: 16 }}>Law <span style={{ color: '#0f0f0f' }}>OSS</span></span>
        </Link>
        <Link href="/signup" style={{
          padding: '0 16px', height: 36, display: 'inline-flex', alignItems: 'center',
          background: '#0f0f0f', borderRadius: 7, fontSize: 13.5, textDecoration: 'none', color: '#fff',
        }}>Get started free</Link>
      </nav>

      <div style={{ maxWidth: 740, margin: '0 auto', padding: '60px 24px 100px' }}>
        <div style={{ marginBottom: 48 }}>
          <h1 style={{ fontSize: 36, fontWeight: 800, color: '#0f0f0f', lineHeight: 1.15, marginBottom: 12 }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: 13.5, color: '#888', lineHeight: 1.6, margin: 0 }}>
            Last updated: June 2026 · These terms apply to all users of lawoss.com and self-hosted deployments.
          </p>
        </div>

        {/* Important notice box */}
        <div style={{
          background: '#0f0f0f', borderRadius: 12, padding: '20px 24px', marginBottom: 48,
        }}>
          <p style={{ fontSize: 13.5, color: '#fff', lineHeight: 1.7, margin: 0, fontWeight: 500 }}>
            <strong style={{ color: '#fff' }}>Important:</strong>{' '}
            Law OSS is open-source software, not a law firm. AI output is not legal advice.
            By using this platform you agree to these terms in full. If you do not agree, do not use the service.
          </p>
        </div>

        {sections.map(section => (
          <div key={section.title} style={{ marginBottom: 36, paddingBottom: 36, borderBottom: '1px solid rgba(0,0,0,0.07)' }}>
            <h2 style={{ fontSize: 16, fontWeight: 700, color: '#0f0f0f', lineHeight: 1.4, marginBottom: 10 }}>
              {section.title}
            </h2>
            <p style={{ fontSize: 14, color: '#444', lineHeight: 1.75, margin: 0 }}>
              {section.body}
            </p>
          </div>
        ))}

        <div style={{
          background: '#f5f5f5', border: '1px solid rgba(0,0,0,0.08)',
          borderRadius: 12, padding: '20px 24px', marginTop: 16,
        }}>
          <p style={{ fontSize: 13.5, color: '#555', lineHeight: 1.6, margin: 0 }}>
            Questions about these terms? Open an issue on{' '}
            <a href="https://github.com/YOUR_USERNAME/law-oss" target="_blank" style={{ color: '#0f0f0f', fontWeight: 600 }}>
              GitHub
            </a>
            {' '}or contact the project maintainers.
          </p>
        </div>
      </div>
    </div>
  )
}
